### ISSUE TITLE
hcs_cluster resource is not idempotent for Development clusters

### ISSUE THREAD

**Issue by assareh** [hashicorp/terraform-provider-hcs#63]
### Terraform Version
Terraform v0.14.9

### Affected Resource(s)
- hcs_cluster

### Terraform Configuration Files
```hcl
resource "hcs_cluster" "example" {
  resource_group_name      = azurerm_resource_group.hcs.name
  managed_application_name = "hcs-cluster"
  email                    = "me@nobody.com"
  cluster_mode             = "Development"
  consul_datacenter        = "dc1"
  consul_external_endpoint = true
  min_consul_version       = data.hcs_consul_versions.default.recommended
  plan_name                = data.hcs_plan_defaults.default.plan_name
  tags                     = local.common_tags
}
```

### Expected Behavior
The resource should be idempotent. Subsequent plans/applies that contain no changes should not modify the HCS cluster.

### Actual Behavior
first terraform apply creates the cluster successfully
however during the next refresh the `cluster_mode` changes to `PRODUCTION`. 

```
Terraform v0.14.9
Configuring remote state backend...
Initializing Terraform configuration...
azurerm_resource_group.hcs: Refreshing state... []
hcs_cluster.example: Refreshing state... []

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # hcs_cluster.example must be replaced
-/+ resource "hcs_cluster" "example" {
      ~ blob_container_name            = "blobzdso7arbudgwu" -> (known after apply)
      ~ cluster_mode                   = "PRODUCTION" -> "Development" # forces replacement
...
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `terraform apply`

**Comment by alexmunda** [comment]
Hey @assareh ! Thanks for reporting this. It should be fixed with https://github.com/hashicorp/terraform-provider-hcs/pull/70. Will close this once https://github.com/hashicorp/terraform-provider-hcs/pull/70 is merged and makes it into the next release.

**Comment by scul859** [comment]
@alexmunda  any idea when the fix is going to be released? I am currently struggling with the same issue as it effectively prevents us from setting up hcs development environments due to the much higher cost of production clusters.

**Comment by alexmunda** [comment]
@scul859 I reached out to the Consul Cloud team and they are planning to get the release out this coming week or the next, sorry about the delay!

**Comment by alexmunda** [comment]
`0.3.0` has been released https://registry.terraform.io/providers/hashicorp/hcs/latest
